### PR TITLE
Turbine fix part 1

### PR DESCRIPTION
**Pull request by MCTian-mi**
This PR:

- disables the extended rotation of susy turbines.
- adds classes `VariantAxialRotatableBlock` and `VariantDirectionalRotatableBlock`, for turbine fix part 2
- ~makes the turbine rotor block omnidirectional.~ Moved to part 2
- ~makes the copper alternator coil & the separator rotor axial-directional (3 axial directions)~ Moved to part 2
- registers custom wrench behavior for above three blocks. (meaning that they now shows that 9-sectioned highlight grid when looking at this block while holding a wrench)
- ~makes susy large turbines only accept turbine rotor block in one direction instead of two since I think it makes sense.~ Moved to part 2
- adds `@Override` to `allowsExtendedFacing()` methods in some multis where I forgot to add. (sorry for that)
- stops mobs from spawning on some susy blocks, together with some tiny refactors.
- makes turbine &  gravity separators auto correct the orientation of the directional blocks in their structures.

This PR has been tested only in a dev environment.

### CODE REVIEW

**Comment by MCTian-mi** [comment]
wait untill the meta issue is solved

**Comment by MCTian-mi** [comment]
> wait untill the meta issue is solved

Ok now this is my plan for the directional blocks:

- Part 1 (for the next susy update): make turbines and gravity separators auto correct the direction of the blocks, forcing them to point at either `NORTH` or `EAST`, reducting possible meta value from 4 to 2.

- Part 2 (for the update after the next update): makes the copper alternator coil & the separator rotor axial-directional; makes the turbine rotor block omnidirectional, since new possible meta value (either 3 or 6) is larger than 2 after the Part 1 fix, we can easily make the change without delecting these blocks from existing saves.

**Comment by MCTian-mi** [comment]
this is now ready to get merged

**Review by bruberu — APPROVED** [review]
Cool, although I think I need to update the CEu dependency soon.

**Pull request merged**
