### PR TITLE
Make the drill head non-rotatable(non important/bad quality)

### PR DESCRIPTION
**Pull request by Fyrstikkeske**
i couldnt get intellij to work with susycore, so i couldnt test if it actually works. this is the update, feel free to decline for any reason. Though if you you need the drill head to rotate, add a note into the book saying the drill head needs to face north.

### CODE REVIEW

**Comment by loxoDev** [comment]
Could you please explain why this is necessary? Does it like only take very specific rotations? I think thats what you mean with the note right?

**Comment by Fyrstikkeske** [comment]
yeah, so basically the drill only works if its rotated to the north.

**Comment by bruberu** [comment]
Currently, this doesn't seem to compile.

**Comment by Fyrstikkeske** [comment]
im unable to properly work on this, so i'll close this pull request.

**Pull request closed without merging**
