### PR TITLE
Add makeCharged() wrapper

### PR DESCRIPTION
**Pull request by trexxet**
Would be used in GS for some battery types:
```
    .outputs(SuSyUtility.makeCharged(metaitem('battery.lead_acid')))
```

### CODE REVIEW

**Comment by trexxet** [comment]
Pls check it thoroughly as it's my first or second time writing java stuff

**Comment by trexxet** [comment]
> why put this in susycore tho, you can just put it in grs

image

Idk, just thought that that function is not a subject to potential changes, so we'd save a bit loading time if we use it compiled, not interpreted

**Comment by MCTian-mi** [comment]
> > why put this in susycore tho, you can just put it in grs
> 
> image
> 
> Idk, just thought that that function is not a subject to potential changes, so we'd save a bit loading time if we use it compiled, not interpreted

grs now caches compiled classes, so it won't be much of an issue

**Comment by trexxet** [comment]
So should I move that in GS, or can it be left as is?

**Comment by MCTian-mi** [comment]
> So should I move that in GS, or can it be left as is?

for me I'd suggest to port this to grs, it makes more sense to me, and afterall it probably won't even need any extra code adjustments
but if you really don't want to port this to grs, I'm fine with it being in susycore

**Comment by trexxet** [comment]
Ok, moved it to GS without any problems, thanks

**Pull request closed without merging**
