### PR TITLE
multblock ore/fluid drill should be protected from weather now

### PR DESCRIPTION
**Pull request by trainvoi**
code taken from drone pad's file:
https://github.com/SymmetricDevs/Susy-Core/blob/main/src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityDronePad.java#L42

### CODE REVIEW

**Comment by MCTian-mi** [comment]
might need to add this to all our multis

**Comment by trainvoi** [comment]
> might need to add this to all our multis

which multiblocks do you want to add weather protection feature?

**Comment by MCTian-mi** [comment]
> > might need to add this to all our multis
> 
> which multiblocks do you want to add weather protection feature?

just check which multis have overridden the weather proof method but don't have the multiblockpart method in it

**Review by bruberu — APPROVED** [review]
Checking over the other classes, these seem fine.

**Pull request merged**
